# tests/test_profile_advisor.py
import io
import json
import zipfile
import pytest
from pathlib import Path
from unittest.mock import MagicMock
from agents.profile_advisor import ProfileAdvisorAgent
from tools.calibration_db import CalibrationDB


@pytest.fixture
def db(tmp_path):
    db = CalibrationDB(tmp_path / "calibration_db.json")
    db.set_baseline("ELEGOO PLA+ High Speed", "0.4mm",
                    nozzle_temp=225, bed_temp=60, flow_rate=0.98,
                    pressure_advance=0.042, max_speed=150, cooling_fan=100)
    for _ in range(5):
        db.add_run("ELEGOO PLA+ High Speed", "0.4mm",
                   {"overall": 0.91, "passed": True, "phase": "calibrate"})
    return db


@pytest.fixture
def fake_3mf(tmp_path) -> Path:
    path = tmp_path / "cube.3mf"
    gcode = b"""; generated by OrcaSlicer
; filament_type = PLA
; total_layer_count = 100
; layer_height = 0.2
; support_material = 0
M73 P0 R10
G28
G1 Z0.2 F600
G1 X10 Y10 E1.5
"""
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("Metadata/plate_1.gcode", gcode)
        zf.writestr("Metadata/thumbnail.png", b"FAKEPNG")
    return path


def _mock_client(diff_json: dict):
    client = MagicMock()
    block = MagicMock()
    block.text = json.dumps(diff_json)
    resp = MagicMock()
    resp.content = [block]
    client.messages.create.return_value = resp
    return client


_DIFF = {
    "recommendations": [
        {"param": "layer_height", "current": 0.2, "suggested": 0.15, "reason": "Better surface finish for small details"},
    ],
    "summary": "Reduce layer height for improved quality on this geometry."
}


def test_advise_returns_recommendations(db, fake_3mf):
    agent = ProfileAdvisorAgent(_mock_client(_DIFF), db)
    result = agent.advise(fake_3mf, "ELEGOO PLA+ High Speed", "0.4mm")
    assert len(result["recommendations"]) == 1
    assert result["recommendations"][0]["param"] == "layer_height"


def test_advise_includes_baseline_in_prompt(db, fake_3mf):
    client = _mock_client(_DIFF)
    agent = ProfileAdvisorAgent(client, db)
    agent.advise(fake_3mf, "ELEGOO PLA+ High Speed", "0.4mm")
    prompt = client.messages.create.call_args[1]["messages"][0]["content"]
    assert "225" in prompt  # nozzle_temp in baseline
    assert "0.4mm" in prompt


def test_advise_includes_gcode_stats_in_prompt(db, fake_3mf):
    client = _mock_client(_DIFF)
    agent = ProfileAdvisorAgent(client, db)
    agent.advise(fake_3mf, "ELEGOO PLA+ High Speed", "0.4mm")
    prompt = client.messages.create.call_args[1]["messages"][0]["content"]
    assert "100" in prompt  # total_layer_count


def test_advise_raises_on_missing_filament_entry(fake_3mf, tmp_path):
    db = CalibrationDB(tmp_path / "empty.json")
    agent = ProfileAdvisorAgent(_mock_client(_DIFF), db)
    with pytest.raises(ValueError, match="No calibration data"):
        agent.advise(fake_3mf, "Unknown Filament", "0.4mm")
